// logged in user
export const SET_USER = 'SET_USER';

// routing, info
export const SET_VIEW = 'SET_VIEW';
export const RETURN_TO_PREVIOUS_VIEW = 'RETURN_TO_PREVIOUS_VIEW';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_FETCHING = 'SET_FETCHING';
export const SET_ACTIVE_BID = 'SET_ACTIVE_BID';
export const SET_JUST_ADDED_OBJECT = 'SET_JUST_ADDED_OBJECT';

// data store
export const RESET_STORE = 'RESET_STORE';
export const SET_DATA = 'SET_DATA';

// box
export const ADD_TO_BOX = 'ADD_TO_BOX';
export const REMOVE_FROM_BOX = 'REMOVE_FROM_BOX';
export const EMPTY_BOX = 'EMPTY_BOX';
export const SELECT_BOX_ITEM = 'SELECT_BOX_ITEM';

// projects
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const SHOW_PROJECT = 'SHOW_PROJECT';
export const SHOW_PROJECT_NEXT = 'SHOW_PROJECT_NEXT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const CHANGE_PROJECT_EDIT_DATA = 'CHANGE_PROJECT_EDIT_DATA';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';

export const SET_PROJECTS_FILTER = 'SET_PROJECTS_FILTER';
export const SET_PROJECTS_SEARCH = 'SET_PROJECTS_SEARCH';
export const SET_PROJECTS_SORT = 'SET_PROJECTS_SORT';
export const SET_ACTIVE_BID_SEARCH = 'SET_ACTIVE_BID_SEARCH';
export const SET_ACTIVE_BID_SORT = 'SET_ACTIVE_BID_SORT';

//persons
export const SELECT_PERSON = 'SELECT_PERSON';
export const SHOW_PERSON = 'SHOW_PERSON';
export const SHOW_PERSON_NEXT = 'SHOW_PERSON_NEXT';
export const EDIT_PERSON = 'EDIT_PERSON';
export const CHANGE_PERSON_EDIT_DATA = 'CHANGE_PERSON_EDIT_DATA';
export const ADD_PERSON = 'ADD_PERSON';
export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';

export const SET_PERSONS_FILTER = 'SET_PERSONS_FILTER';
export const SET_PERSONS_SEARCH = 'SET_PERSONS_SEARCH';
export const SET_PERSONS_SORT = 'SET_PERSONS_SORT';

//companies
export const SELECT_COMPANY = 'SELECT_COMPANY';
export const SHOW_COMPANY = 'SHOW_COMPANY';
export const SHOW_COMPANY_NEXT = 'SHOW_COMPANY_NEXT';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const CHANGE_COMPANY_EDIT_DATA = 'CHANGE_COMPANY_EDIT_DATA';
export const ADD_COMPANY = 'ADD_COMPANY';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';

export const SET_COMPANIES_FILTER = 'SET_COMPANIES_FILTER';
export const SET_COMPANIES_SEARCH = 'SET_COMPANIES_SEARCH';
export const SET_COMPANIES_SORT = 'SET_COMPANIES_SORT';