// logged in user
export const SET_USER = 'SET_USER';

// routing, info
export const SET_VIEW = 'SET_VIEW';
export const RETURN_TO_PREVIOUS_VIEW = 'RETURN_TO_PREVIOUS_VIEW';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_FETCHING = 'SET_FETCHING';
export const EDIT_ITEM = 'EDIT_ITEM';

// data store
export const RESET_STORE = 'RESET_STORE';
export const SET_DATA = 'SET_DATA';

// box
export const ADD_TO_BOX = 'ADD_TO_BOX';
export const REMOVE_FROM_BOX = 'REMOVE_FROM_BOX';
export const EMPTY_BOX = 'EMPTY_BOX';
export const SELECT_BOX_ITEM = 'SELECT_BOX_ITEM';

// projects
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const SELECT_PROJECT_NEXT = 'SELECT_PROJECT_NEXT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';

export const SET_PROJECTS_FILTER = 'SET_PROJECTS_FILTER';
export const SET_PROJECTS_SEARCH = 'SET_PROJECTS_SEARCH';
export const SET_PROJECTS_SORT = 'SET_PROJECTS_SORT';

//people
export const SELECT_PERSON = 'SELECT_PERSON';
export const SELECT_PERSON_NEXT = 'SELECT_PERSON_NEXT';
export const EDIT_PERSON = 'EDIT_PERSON';
export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const REMOVE_PERSON = 'REMOVE_PERSON';

export const SET_PEOPLE_FILTER = 'SET_PEOPLE_FILTER';
export const SET_PEOPLE_SEARCH = 'SET_PEOPLE_SEARCH';
export const SET_PEOPLE_SORT = 'SET_PEOPLE_SORT';

//companies
export const SELECT_COMPANY = 'SELECT_COMPANY';
export const SELECT_COMPANY_NEXT = 'SELECT_COMPANY_NEXT';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';

export const SET_COMPANIES_FILTER = 'SET_COMPANIES_FILTER';
export const SET_COMPANIES_SEARCH = 'SET_COMPANIES_SEARCH';
export const SET_COMPANIES_SORT = 'SET_COMPANIES_SORT';