export const DEFAULT_MESSAGE_TIMEOUT_MS = 0;
export const SHOW_MESSAGE_ON_SUCCESS = false;
export const SCHEDULED_DATA_REFRESH_TIME_MS = 300000;
export const VALIDATION_DELAY_MS = 500;

export const TABLE_SCROLLBARS_AUTO_HIDE_TIMEOUT = 800;
export const TABLE_SCROLLBARS_AUTO_HIDE_DURATION = 200;

export const TABLE_PAGE_SIZE_PERSON = 50;
export const TABLE_PAGE_SIZE_COMPANY = 50;
export const TABLE_PAGE_SIZE_PROJECT = 50;