export const USER_FILTER = 'USER_FILTER';
export const ACTIVE_PROJECTS_FILTER = 'ACTIVE_PROJECTS_FILTER';
export const NON_ACTIVE_PROJECTS_FILTER = 'NON_ACTIVE_PROJECTS_FILTER';
export const AWARDED_PROJECTS_FILTER = 'WARDED_PROJECTS_FILTER';
export const NOT_AWARDED_PROJECTS_FILTER = 'NOT_WARDED_PROJECTS_FILTER';