export const PROJECTS_LIST = 'PROJECTS_LIST';
export const PROJECT_DETAIL = 'PROJECT_DETAIL';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_DETAIL_NEXT = 'PROJECT_DETAIL_NEXT';

export const PEOPLE_LIST = 'PEOPLE_LIST';
export const PERSON_DETAIL = 'PERSON_DETAIL';
export const PERSON_EDIT = 'PERSON_EDIT';
export const PERSON_DETAIL_NEXT = 'PROJECT_DETAIL_NEXT';

export const COMPANIES_LIST = 'COMPANIES_LIST';
export const COMPANY_DETAIL = 'COMPANY_DETAIL';
export const COMPANY_EDIT = 'COMPANY_EDIT';
export const COMPANY_DETAIL_NEXT = 'PROJECT_DETAIL_NEXT';

export const BOX = 'BOX';
export const BOX_PROJECT_DETAIL = 'BOX_PROJECT_DETAIL';
export const BOX_PROJECT_EDIT = 'BOX_PROJECT_EDIT';