export const PROJECT_LIST = 'PROJECT_LIST';
export const PROJECT_DETAIL = 'PROJECT_DETAIL';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_NEW = 'PROJECT_NEW';
export const PROJECT_DETAIL_NEXT = 'PROJECT_DETAIL_NEXT';

export const PERSON_LIST = 'PERSON_LIST';
export const PERSON_DETAIL = 'PERSON_DETAIL';
export const PERSON_EDIT = 'PERSON_EDIT';
export const PERSON_NEW = 'PERSON_NEW';
export const PERSON_DETAIL_NEXT = 'PERSON_DETAIL_NEXT';

export const COMPANY_LIST = 'COMPANY_LIST';
export const COMPANY_DETAIL = 'COMPANY_DETAIL';
export const COMPANY_EDIT = 'COMPANY_EDIT';
export const COMPANY_NEW = 'COMPANY_NEW';
export const COMPANY_DETAIL_NEXT = 'COMPANY_DETAIL_NEXT';

export const BOX_LIST = 'BOX_LIST';