
//K2 projects
// export const FETCH_K2_PROJECTS_BEGIN = "FETCH_K2_PROJECTS_BEGIN";
// export const FETCH_K2_PROJECTS_SUCCESS = "FETCH_K2_PROJECTS_SUCCESS";
// export const FETCH_K2_PROJECTS_FAILURE = "FETCH_K2_PROJECTS_FAILURE";

//projects
// export const FETCH_AD_PROJECTS_BEGIN = "FETCH_AD_PROJECTS_BEGIN";
// export const FETCH_AD_PROJECTS_SUCCESS = "FETCH_AD_PROJECTS_SUCCESS";
// export const FETCH_AD_PROJECTS_FAILURE = "FETCH_AD_PROJECTS_FAILURE";

//AD Group Members
//export const FETCH_AD_GROUPS_MEMBERS_SUCCESS = "FETCH_AD_GROUPS_MEMBERS_SUCCESS";
// export const FETCH_AD_PROJECTS_SUCCESS = "FETCH_AD_PROJECTS_SUCCESS";
// export const FETCH_AD_PROJECTS_FAILURE = "FETCH_AD_PROJECTS_FAILURE";
export const SET_AD_GROUP_MEMBER = "SET_AD_GROUP_MEMBER"

//Active project
// export const SET_ACTIVE_PROJECT = "SET_ACTIVE_PROJECT";
// export const CLEAN_ACTIVE_PROJECT = "CLEAN_ACTIVE_PROJECT";

//Confirmed groupMembers
// export const SET_CONFIRMED_GROUP_MEMBERS = "SET_CONFIRMED_GROUP_MEMBERS";

//Editing groupMembers
// export const SET_ALL_EDITING_GROUP_MEMBERS = "SET_ALL_EDITING_GROUP_MEMBERS";
// export const ADD_ONE_EDIT_GROUP_MEMBER = "ADD_ONE_EDIT_GROUP_MEMBER";
// export const SET_EDITING_GROUP_MEMBERS = "SET_EDITING_GROUP_MEMBERS";
// export const DELETE_MEMBER_EDIT_GROUP = "DELETE_MEMBER_EDIT_GROUP";


//get group members
export const FETCH_MEMBERS_BEGIN = "FETCH_MEMBERS_BEGIN";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAILURE = "FETCH_MEMBERS_FAILURE";

//add group members
export const FETCH_ADD_MEMBERS_BEGIN = "FETCH_ADD_MEMBERS_BEGIN";
export const FETCH_ADD_MEMBERS_SUCCESS = "FETCH_ADD_MEMBERS_SUCCESS";
export const FETCH_ADD_MEMBERS_FAILURE = "FETCH_ADD_MEMBERS_FAILURE";


//role candidates
// export const FETCH_CANDIDATES_BEGIN = "FETCH_CANDIDATES_BEGIN";
// export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
// export const FETCH_CANDIDATES_FAILURE = "FETCH_CANDIDATES_FAILURE";